name: Build Installer for Windows and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Application
        id: build
        run: |
          cargo build --release
          Add-Content -Path $env:GITHUB_OUTPUT -Value "APP_VERSION=v$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')"

      - name: Build Installer
        env:
          APP_NAME: folio
          APP_VERSION: ${{ steps.build.outputs.APP_VERSION }}
          APP_PUBLISHER: StorkKershaw
          APP_URL: "${{ github.server_url }}/${{ github.repository }}"
          OUTPUT_DIR: target\release
        uses: Minionguyjpro/Inno-Setup-Action@main
        with:
          path: installer.iss
          options: |
            /O+
            /DAppName=${{ env.APP_NAME }}
            /DAppVersion=${{ env.APP_VERSION }}
            /DAppPublisher=${{ env.APP_PUBLISHER }}
            /DAppURL=${{ env.APP_URL }}
            /DOutputDir=${{ env.OUTPUT_DIR }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: "**/folio ${{ github.ref_name }}.exe"
